//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CallCenterAutomation.Models.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CallCenterAutomationEntities1 : DbContext
    {
        public CallCenterAutomationEntities1()
            : base("name=CallCenterAutomationEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BANKACCOUNTTYPE> BANKACCOUNTTYPES { get; set; }
        public virtual DbSet<BANK> BANKS { get; set; }
        public virtual DbSet<COMPANy> COMPANIES { get; set; }
        public virtual DbSet<DEPARTMENT> DEPARTMENTS { get; set; }
        public virtual DbSet<EDUCATIONSTATUS> EDUCATIONSTATUSES { get; set; }
        public virtual DbSet<EMPLOYEE> EMPLOYEES { get; set; }
        public virtual DbSet<EMPLOYEETITLE> EMPLOYEETITLES { get; set; }
        public virtual DbSet<EXPECTATION> EXPECTATIONS { get; set; }
        public virtual DbSet<MARRIAGESTATUS> MARRIAGESTATUSES { get; set; }
        public virtual DbSet<PAYMENT> PAYMENTS { get; set; }
        public virtual DbSet<PROXIMITYDEGREE> PROXIMITYDEGREES { get; set; }
        public virtual DbSet<REQUESTHEADER> REQUESTHEADERS { get; set; }
        public virtual DbSet<REQUESTPROCESS> REQUESTPROCESSES { get; set; }
        public virtual DbSet<REQUEST> REQUESTS { get; set; }
        public virtual DbSet<REQUESTSTATUS> REQUESTSTATUSES { get; set; }
        public virtual DbSet<ROLEMASTER> ROLEMASTERS { get; set; }
        public virtual DbSet<TASKPROCESS> TASKPROCESSES { get; set; }
        public virtual DbSet<TASKSTATUS> TASKSTATUSES { get; set; }
        public virtual DbSet<USERROLEMAPPING> USERROLEMAPPINGS { get; set; }
        public virtual DbSet<USER> USERS { get; set; }
        public virtual DbSet<WORKINGSTATUS> WORKINGSTATUSES { get; set; }
        public virtual DbSet<TASK> TASKS { get; set; }
    }
}
