//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CallCenterAutomation.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class REQUESTPROCESS
    {
        public int ID { get; set; }
        public Nullable<int> RequestID { get; set; }
        public Nullable<int> ResponsibleUserID { get; set; }
        public string SolutionNote { get; set; }
        public Nullable<System.DateTime> ProcessTime { get; set; }
    
        public virtual REQUEST REQUEST { get; set; }
        public virtual USER USER { get; set; }
    }
}
