//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CallCenterAutomation.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TASK
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TASK()
        {
            this.TASKPROCESSES = new HashSet<TASKPROCESS>();
        }
    
        public int ID { get; set; }
        public string Detail { get; set; }
        public Nullable<int> TaskStatusID { get; set; }
        public Nullable<System.DateTime> AddedTime { get; set; }
        public string ResponsibleUsers { get; set; }
        public Nullable<int> DepartmentID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TASKPROCESS> TASKPROCESSES { get; set; }
        public virtual TASKSTATUS TASKSTATUS { get; set; }
    }
}
