//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CallCenterAutomation.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TASKPROCESS
    {
        public int ID { get; set; }
        public Nullable<int> TaskID { get; set; }
        public Nullable<System.DateTime> LastProcessTime { get; set; }
        public Nullable<int> ResponsibleUserID { get; set; }
        public string SolutionDetail { get; set; }
    
        public virtual USER USER { get; set; }
        public virtual TASK TASK { get; set; }
    }
}
